Logs:
    type: entity
    table: logs
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
                strategy: IDENTITY
        title:
            type: string
            length: 100
            fixed: false
            nullable: true
        description:
            type: text
            nullable: true
        model:
            type: string
            length: 50
            fixed: false
            nullable: true
        foreignKey:
            type: integer
            unsigned: true
            nullable: true
            column: foreign_key
        action:
            type: string
            length: 50
            fixed: false
            nullable: true
        change:
            type: text
            nullable: true
        created:
            type: datetime
            nullable: true
    manyToOne:
        user:
            targetEntity: Users
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
