SchemaMigrations:
    type: entity
    table: schema_migrations
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        class:
            type: string
            length: 255
            fixed: false
            nullable: true
        type:
            type: string
            length: 50
            fixed: false
            nullable: true
        created:
            type: datetime
            nullable: true
    lifecycleCallbacks: {  }
